### ISSUE TITLE
bug: Failed to deploy CDK with aws-cdk 2.178.0 (or newer) and aws-cdk-local 2.19.2 from a dedicated docker container

### ISSUE THREAD

**Issue by GiantKouKou** [localstack/aws-cdk-local#110]
Hello,

For our project we are using a docker compose file to start localstack and deploy multiple cdk.

It was working great until **aws-cdk 2.178.0** and **aws-cdk-local 2.19.2**.

Here is a sample of our docker compose:

```yaml
# Localstack container
localstack:
  image: public.ecr.aws/localstack/localstack:4.2.0
  ports:
    - "4566:4566" # LocalStack Gateway
    - "4510-4559:4510-4559" # external services port range
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

# Container that deploy CDK in localstack
cdk-1:
  image: my-cdk-image
  container_name: cdk-1
  restart: on-failure
  environment:
    AWS_ENDPOINT_URL: http://localstack:4566
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
    AWS_DEFAULT_REGION: us-east-1
  entrypoint: npx cdklocal deploy --require-approval=never
  depends_on:
    localstack:
      condition: service_started
    localstack-bootstrap:
      condition: service_completed_successfully
  links:
    - localstack
```

I get the following log during the deployment, it seems it is trying to publish assets on the wrong ip.

```
[Warning at /my-cdk-01/rFunction1/MyFunction/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup [ack: @aws-cdk/aws-ec2:ipv4IgnoreEgressRule]
[Warning at /my-cdk-01/rFuncion2/MyFunction/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup [ack: @aws-cdk/aws-ec2:ipv4IgnoreEgressRule]
[Warning at /my-cdk-01/rFunction3/MyFunction/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup [ack: @aws-cdk/aws-ec2:ipv4IgnoreEgressRule]
[Warning at /my-cdk-01/rFunction4/MyFunction/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup [ack: @aws-cdk/aws-ec2:ipv4IgnoreEgressRule]
[Warning at /my-cdk-01/rFunction5/MyFunction/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup [ack: @aws-cdk/aws-ec2:ipv4IgnoreEgressRule]
[Warning at /my-cdk-01/rFunction6/MyFunction/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup [ack: @aws-cdk/aws-ec2:ipv4IgnoreEgressRule]

✨  Synthesis time: 1.11s

my-cdk-01: start: Building 135f904790cffb6a12ca58470449b5a6dd58093351fd3b19b121d8b112c6b0a4
my-cdk-01: success: Built 135f904790cffb6a12ca58470449b5a6dd58093351fd3b19b121d8b112c6b0a4
my-cdk-01: start: Building 2819175352ad1ce0dae768e83fc328fb70fb5f10b4a8ff0ccbcb791f02b0716d
my-cdk-01: success: Built 2819175352ad1ce0dae768e83fc328fb70fb5f10b4a8ff0ccbcb791f02b0716d
my-cdk-01: start: Building faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6
my-cdk-01: success: Built faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6
my-cdk-01: start: Building 45bb16c493de059e812a714e4db921a6c5fed884469ff3d8b386ff1b922ac143
my-cdk-01: success: Built 45bb16c493de059e812a714e4db921a6c5fed884469ff3d8b386ff1b922ac143
my-cdk-01: start: Publishing 135f904790cffb6a12ca58470449b5a6dd58093351fd3b19b121d8b112c6b0a4:000000000000-us-east-1
my-cdk-01: start: Publishing 2819175352ad1ce0dae768e83fc328fb70fb5f10b4a8ff0ccbcb791f02b0716d:000000000000-us-east-1
my-cdk-01: start: Publishing faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6:000000000000-us-east-1
my-cdk-01: start: Publishing 45bb16c493de059e812a714e4db921a6c5fed884469ff3d8b386ff1b922ac143:000000000000-us-east-1
my-cdk-01: fail: connect ECONNREFUSED 127.0.0.1:4566
my-cdk-01: fail: connect ECONNREFUSED 127.0.0.1:4566
my-cdk-01: fail: connect ECONNREFUSED 127.0.0.1:4566
my-cdk-01: fail: connect ECONNREFUSED 127.0.0.1:4566

NOTICES         (What's this? https://github.com/aws/aws-cdk/wiki/CLI-Notices)

32775   (cli): CLI versions and CDK library versions have diverged

        Overview: Starting in CDK 2.179.0, CLI versions will no longer be in
                  lockstep with CDK library versions. CLI versions will now be
                  released as 2.1000.0 and continue with 2.1001.0, etc.

        Affected versions: cli: >=2.0.0 <=2.1005.0

        More information at: https://github.com/aws/aws-cdk/issues/32775


If you don’t want to see a notice anymore, use "cdk acknowledge <id>". For example, "cdk acknowledge 32775".
Failed to publish asset faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6:000000000000-us-east-1
```

Tell me if you need more information to reproduce

Thank you

**Comment by AlejandroBudy** [comment]
I had the same problem and I was able to fix it by adding both `AWS_ENDPOINT_URL` and `AWS_ENDPOINT_URL_S3`

**Comment by GiantKouKou** [comment]
If I set **`AWS_ENDPOINT_URL_S3`** to **`http://localstack:4566`**, the error message is a bit different, but it's still not working

```
my-cdk-01: start: Building 58833a01454fbb8196493dc049c8cb5daa026b3663daa8613320dc88f01f4561
my-cdk-01: success: Built 58833a01454fbb8196493dc049c8cb5daa026b3663daa8613320dc88f01f4561
my-cdk-01: start: Building 2819175352ad1ce0dae768e83fc328fb70fb5f10b4a8ff0ccbcb791f02b0716d
my-cdk-01: success: Built 2819175352ad1ce0dae768e83fc328fb70fb5f10b4a8ff0ccbcb791f02b0716d
my-cdk-01: start: Building faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6
my-cdk-01: success: Built faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6
my-cdk-01: start: Publishing 58833a01454fbb8196493dc049c8cb5daa026b3663daa8613320dc88f01f4561:000000000000-us-east-1
my-cdk-01: start: Building ef9533744a965bbf9482db9982b1e221a05bcf0b813732716a3febcbde730229
my-cdk-01: success: Built ef9533744a965bbf9482db9982b1e221a05bcf0b813732716a3febcbde730229
my-cdk-01: start: Publishing ef9533744a965bbf9482db9982b1e221a05bcf0b813732716a3febcbde730229:000000000000-us-east-1
my-cdk-01: start: Publishing 2819175352ad1ce0dae768e83fc328fb70fb5f10b4a8ff0ccbcb791f02b0716d:000000000000-us-east-1
my-cdk-01: start: Publishing faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6:000000000000-us-east-1
my-cdk-01: fail: getaddrinfo ENOTFOUND cdk-hnb659fds-assets-000000000000-us-east-1.localstack
my-cdk-01: fail: getaddrinfo ENOTFOUND cdk-hnb659fds-assets-000000000000-us-east-1.localstack
my-cdk-01: fail: getaddrinfo ENOTFOUND cdk-hnb659fds-assets-000000000000-us-east-1.localstack
my-cdk-01: fail: getaddrinfo ENOTFOUND cdk-hnb659fds-assets-000000000000-us-east-1.localstack
Failed to publish asset 2819175352ad1ce0dae768e83fc328fb70fb5f10b4a8ff0ccbcb791f02b0716d:000000000000-us-east-1
```

**Comment by AlejandroBudy** [comment]
yes I had that error as well, you have to use the IP instead, that solves the problem

**Comment by GiantKouKou** [comment]
Thanks a lot for your help, it works with IP, I defined a network with static IPs in my docker compose

```yaml
# Localstack container
localstack:
  image: public.ecr.aws/localstack/localstack:4.2.0
  ports:
    - "4566:4566" # LocalStack Gateway
    - "4510-4559:4510-4559" # external services port range
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    localstack:
      ipv4_address: 10.5.0.5

# Container that deploy CDK in localstack
cdk-1:
  image: my-cdk-image
  container_name: cdk-1
  restart: on-failure
  environment:
    AWS_ENDPOINT_URL: http://10.5.0.5:4566
    AWS_ENDPOINT_URL_S3: http://10.5.0.5:4566
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
    AWS_DEFAULT_REGION: us-east-1
  entrypoint: npx cdklocal deploy --require-approval=never
  depends_on:
    localstack:
      condition: service_started
    localstack-bootstrap:
      condition: service_completed_successfully
  networks:
    - localstack

networks:
  localstack:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
```
