### ISSUE TITLE
Unable to deploy EKS cluster

### ISSUE THREAD

**Issue by okeeffed** [localstack/aws-cdk-local#52]
## The problem

Deploying a basic example of an EKS cluster fails with LocalStack on local.

## The code

The stack comes from the [AWS CDK EKS example](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-eks-readme.html#quick-start).

```ts
import * as eks from "@aws-cdk/aws-eks"
import * as cdk from "@aws-cdk/core"

export class AwsCdkWithTypescriptFoundationsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props)

    // provisiong a cluster
    const cluster = new eks.Cluster(this, "hello-eks", {
      version: eks.KubernetesVersion.V1_21,
    })

    // apply a kubernetes manifest to the cluster
    cluster.addManifest("mypod", {
      apiVersion: "v1",
      kind: "Pod",
      metadata: { name: "mypod" },
      spec: {
        containers: [
          {
            name: "hello",
            image: "paulbouwer/hello-kubernetes:1.5",
            ports: [{ containerPort: 8080 }],
          },
        ],
      },
    })
  }
}
```

## Steps to recreate

1. Add the above code to a TypeScript AWS CDK app
2. Run the following:

```s
$ cdk synth
$ cdk bootstrap
$ cdk deploy
# ... error 
```

The error (as far as I can tell) from the `docker compose` logs:

```
localstack_1  | 2021-08-11T09:30:04:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::Join': ['', ['aws eks get-token --cluster-name ', {'Ref': 'HelloEKS39C624A1'}, ' --region ', {'Ref': 'AWS::Region'}, ' --role-arn ', {'Fn::GetAtt': ['HelloEKSMastersRole53742E60', 'Arn']}]]}} - Unable to fetch details for resource "HelloEKS39C624A1" (attribute "Ref")
localstack_1  | 2021-08-11T09:30:07:DEBUG:localstack.services.cloudformation.cloudformation_api: Executing change set "cdk-deploy-change-set" for stack "AwsCdkWithTypescriptFoundationsStack" with 37 resources ...
localstack_1  | 2021-08-11T09:30:07:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "AwsCdkWithTypescriptFoundationsStack": An error occurred (DependencyViolation) when calling the DeleteRouteTable operation: The routeTable 'rtb-ea506a4e' has dependencies and cannot be deleted. Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1828, in _run
localstack_1  |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1879, in do_apply_changes_in_loop
localstack_1  |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1934, in apply_change
localstack_1  |     result = delete_resource(resource_id, old_stack.resources, stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 984, in delete_resource
localstack_1  |     ec2_client.delete_route_table(RouteTableId=rt['RouteTableId'])
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
localstack_1  |     raise error_class(parsed_response, operation_name)
localstack_1  | botocore.exceptions.ClientError: An error occurred (DependencyViolation) when calling the DeleteRouteTable operation: The routeTable 'rtb-ea506a4e' has dependencies and cannot be deleted.
localstack_1  | 
localstack_1  | 2021-08-11T09:30:07:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Custom::AWSCDK-EKS-Cluster Ref
localstack_1  | 2021-08-11T09:30:07:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::Join': ['', ['aws eks update-kubeconfig --name ', {'Ref': 'HelloEKS39C624A1'}, ' --region ', {'Ref': 'AWS::Region'}, ' --role-arn ', {'Fn::GetAtt': ['HelloEKSMastersRole53742E60', 'Arn']}]]}} - Unable to fetch details for resource "HelloEKS39C624A1" (attribute "Ref")
```

**Comment by okeeffed** [comment]
For some extra info, my `docker-compose.yml` file looks like so:

```yml
version: "2.1"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - HOSTNAME_EXTERNAL=localstack
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_NETWORK=bridge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
```

**Comment by okeeffed** [comment]
Pulled the latest image and this looks to no longer be an issue.

Closing this ticket.

**Comment by okeeffed** [comment]
I messed up -- what worked was when I deployed an ECS cluster, not an EKS cluster!

**Comment by okeeffed** [comment]
Was looking into this a little further and trying to spin up an EKS cluster without the CDK using the `awslocal`.

```s
$ awslocal eks create-cluster --name cluster1 --role-arn r1 --resources-vpc-config '{}'

An error occurred (500) when calling the CreateCluster operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

```

Looking at the logs I see the following:

```s
localstack_1  | 2021-08-17T02:49:25:ERROR:eks_api: Exception on /clusters [POST]
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/eks/eks_api.py", line 62, in load_config
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
localstack_1  |     persist_config=persist_config)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 773, in _get_kube_config_loader
localstack_1  |     'Invalid kube-config file. '
localstack_1  | kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
localstack_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/eks/eks_api.py", line 103, in create_cluster
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/eks/eks_api.py", line 67, in load_config
localstack_1  | Exception: Unable to connect to local Kubernetes cluster: Invalid kube-config file. No configuration found.
localstack_1  | 2021-08-17 02:49:25,808:API: 127.0.0.1 - - [17/Aug/2021 02:49:25] "POST /clusters HTTP/1.1" 500 -
```

Unsure what to make of it. This was some more config work that I was doing:

```s
$ echo $KUBECONFIG                
/Users/dennisokeeffe/.kube/config
```

`cat $KUBECONFIG` displays the following YAML (with some redactions):

```yml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [REDACTED]
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: [REDACTED]
    client-key-data: [REDACTED]
```

`kubectl` works fine with that configuration.

```s
$ kubectl get all 
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   46m
```

No really sure where to go from here :/
